# Use a base image with OpenJDK 17 installed
FROM openjdk:17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the packaged JAR file into the container
COPY ${WORKSPACE}/target/spring-petclinic-*-SNAPSHOT.jar /app/application.jar

# Expose port 8080
EXPOSE 8080

# Command to run the application when the container starts
CMD ["java", "-jar", "/app/application.jar"]
